config/routes.rb
Rails.application.routes.draw do
  get 'routes/index'

  resources :routes do 
    collection do 
      get 'route_names'
    end
  end

   root 'routes#index'

end

app/models/route.rb
class Route < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/routes_controller.rb
class RoutesController < ApplicationController
  def index
  	json_data = '[
 	{ "Timestamp": "24-02-2015 13:42:41", "Name": "TS_A10 8,150Re_AfritS114 Re_IJburglaan", "Velocity": 43, "Length": 1566, "Traveltime": 130 },
 	{ "Timestamp": "24-02-2015 13:42:42", "Name": "TS_A11 8,150Re_AfritS114 Re_IJburglaan", "Velocity": 44, "Length": 1567, "Traveltime": 131 },
 	{ "Timestamp": "24-02-2015 13:42:43", "Name": "TS_A12 8,150Re_AfritS114 Re_IJburglaan", "Velocity": 45, "Length": 1568, "Traveltime": 132 }
 	]'

 	@parsed_json = JSON.parse(json_data)
 	location = params[:name]
 	#@route = Route.new(timestamp: bla, name: bla, )
  	@route = Route.where(name: location)

  	render json: @route
  end

  def show
  	route = Route.find(params[:id])
  end

  def route_names
  	render json: Route.select(:name).uniq
  end

  def new
  	@route = Route.new
	
  end

  def create #opslaan nieuw route
		@route = Route.new(allowed_params)

		if @route.save
			redirect_to routes_path
		else
			render 'new'
		end
	end


	private 
		def allowed_params
			params.require(:route).permit(:timestamp, :name, :velocity, :length , :traveltime)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/routes_helper.rb
module RoutesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TestProject</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/routes/index.html.erb
<% @route.each do |route| %>
	<%= route %>
	<p>Name:<%= route.name %></p>
	<p>Velocity: <%= route.velocity %> </p>
	<p>Length: <%= route.length %> </p>
	<p>Traveltime: <%= route.traveltime %> </p>
	<p>Timestamp: <%= route.timestamp %> </p>
	<hr />
<%end%>

<% @parsed_json.each do |parse| %>
	<p>JSON OBJECT: <%= parse['Timestamp'] %></p>
	
	<hr />
<%end%>

<%= link_to 'Add route', new_route_path %>

app/views/routes/new.html.erb
<%= form_for @route do |f| %>

	<%= f.label :timestamp %> <br />
	<%= f.text_field :timestamp %> <br />
	<%= f.label :name %> <br />
	<%= f.text_field :name %> <br />
	<%= f.label :velocity %> <br />
	<%= f.text_field :velocity %> <br />
	<%= f.label :length %> <br />
	<%= f.text_field :length %> <br />
	<%= f.label :traveltime %> <br />
	<%= f.text_field :traveltime %> <br />

	<%= f.submit %>

<% end %>